env:
  es2021: true
  node: true
extends:
  - airbnb-base
  - plugin:jest/recommended
parserOptions:
  ecmaVersion: 13
  sourceType: module
rules:
  import/extensions: 0
  no-param-reassign:
    - error
    - props: true
      ignorePropertyModificationsFor:
      - app
      - req
      - res

